/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Unified probe task.
 *
 * - Static methods `probeFile` and `probeBuffer` handle the simple cases.
 * - For streams, JS creates an instance, calls `start()`, pushes chunks
 *   via `push()`, then `finish()`.  Chunks flow through a bounded
 *   `tokio::sync::mpsc` channel to a write loop on tokio, providing
 *   backpressure without blocking the JS thread.
 */
export declare class ProbeTask {
  constructor()
  /** Probe a media file by path. */
  static probeFile(path: string): Promise<any>
  /**
   * Probe a media file from raw bytes.
   * Uses custom AVIO — no temp file written to disk.
   */
  static probeBuffer(data: Buffer): Promise<any>
  /**
   * Spawn the FFmpeg blocking probe and the write-loop task.
   * Returns a Promise for the probe result.
   * Must be called exactly once, before any `push()` / `finish()` calls.
   */
  start(): Promise<any>
  /**
   * Push one or more chunks of bytes.  Returns a Promise that resolves to
   * `true` if all chunks were accepted (keep pushing), or `false` if FFmpeg
   * has already finished and no more data is needed.
   */
  push(chunks: Array<Buffer>): Promise<boolean>
  /** Signal that the stream has ended (EOF). */
  finish(): void
}
